version: '3.9'
services:
  webserver:
    container_name: api-php
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html/backend
    ports:
      - "9090:9090"
    depends_on:
      - postgres

  frontend:
    container_name: frontend-vue
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "9000:9000" 
    depends_on:
      - webserver

  postgres:
    image: postgres:latest
    volumes:
    - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store
    ports:
      - "5440:5432" 


      